-- phpMyAdmin SQL Dump
-- version 5.1.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Apr 21, 2021 at 11:44 AM
-- Server version: 10.5.9-MariaDB
-- PHP Version: 8.0.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `super_app`
--

-- --------------------------------------------------------

--
-- Table structure for table `categories`
--

CREATE TABLE `categories` (
  `id` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `categories`
--

INSERT INTO `categories` (`id`, `name`, `description`) VALUES
(1, 'Dla niej', ''),
(2, 'Spódnice', ''),
(3, 'Spodnie', ''),
(4, 'Dla niego', ''),
(5, 'T-shirt', ''),
(6, 'Bluzy i koszule', ''),
(7, 'Buty', ''),
(8, 'Buty', ''),
(9, 'Spodnie', ''),
(10, 'Akcesoria', ''),
(11, 'Płaszcze i kurtki', ''),
(12, 'Akcesoria', ''),
(13, 'Płaszcze i kurtki', ''),
(14, 'Sukienki', ''),
(15, 'Torebki', ''),
(16, 'Karnisze', ''),
(17, 'Rolety', ''),
(18, 'Plisy', ''),
(19, 'Moskitiery', ''),
(20, 'Metaloplastyka', ''),
(21, 'Lorem ipsum 1', ''),
(22, 'Lorem ipsum 2', ''),
(23, 'Lorem ipsum 3', ''),
(24, 'Lorem ipsum 4', ''),
(25, 'Lorem ipsum 5', ''),
(26, 'Lorem ipsum 1', ''),
(27, 'Lorem ipsum 2', ''),
(28, 'Lorem ipsum 3', ''),
(29, 'Lorem ipsum 4', ''),
(30, 'Lorem ipsum 1', ''),
(31, 'Lorem ipsum 2', ''),
(32, 'Lorem ipsum 1', ''),
(33, 'Lorem ipsum 2', ''),
(34, 'Lorem ipsum 3', '');

-- --------------------------------------------------------

--
-- Table structure for table `info`
--

CREATE TABLE `info` (
  `id` int(11) NOT NULL,
  `imported_count` int(11) NOT NULL,
  `import_date` datetime NOT NULL,
  `product_names` text COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` int(11) NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `category_id` int(11) NOT NULL,
  `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `price` float DEFAULT NULL,
  `add_date` datetime DEFAULT NULL,
  `photo_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `name`, `category_id`, `description`, `price`, `add_date`, `photo_url`) VALUES
(96, 'Zegarek z tarczą 5 cm na skórzanym pasku MHT', 10, '<p><span><strong>Opis produktu, który powie więcej, niż sprzedawca</strong><br /><br />W tym miejscu należy wstawić opis produktu, prezentujący jego cechy, właściwości oraz zastosowanie. Klient czytając opis musi dowiedzieć się o nim jak najwięcej. Pamiętaj, że to internet, a nie sklepowa półka. Produktu nie da się wziąć do ręki, dlatego opisz każdy szczegół najdokładniej jak potrafisz. Unikniesz w ten sposób<br />nieporozumień i zwrotów towaru.<br /><br /><strong>W opisie uwzględnij parametry techniczne, ale i opis zastosowania</strong><br /><br />Parametry warto wypunktować, by jak najbardziej ułatwić klientowi zrozumienie specyfiki produktu:<br /><br />- Rodzaj materiału<br />- Wymiary<br />- Kraj produkcji<br />- Dodatkowe właściwości<br />- Dodatkowe cechy charakterystyczne<br />- Dodatkowe informacje na temat wysyłki<br /><br /><strong>Dlaczego opis jest tak ważny</strong><br /><br />Forma przedstawienia asortymentu w sklepie internetowym ma znaczący wpływ na to, czy przekonamy klienta do zakupów w naszym sklepie. Zapewniając unikalne oraz wyczerpujące informacje na temat towaru, zwiększamy liczbę indeksowanych stron naszego sklepu przez wyszukiwarki internetowe np. Google. To właśnie wyszukiwarki zwiększają ruch w naszym sklepie, dlatego zadbajmy o to, aby każdy produkt posiadał wyczerpujący opis. <br /><br />Sklep internetowy, w odróżnieniu od tradycyjnego, nie posiada ekspedienta, który nas wysłucha oraz pomoże w wyborze przedmiotu spełniającego nasze oczekiwania. Istnieje duże prawdopodobieństwo, że klient, który nie znajdzie interesujących go informacji o produkcie, poszuka innego sklepu, a do nas już nie wróci. Opis zastępuje sprzedawcę i wzmacnia pozycję strony w wyszukiwarce - kieruj się tym podczas charakteryzowania produktu.<br /><br />Nie zapomnij o sekcji, która dodatkowo zachęci klienta do zrobienia zakupów u ciebie. Pamiętaj, że możesz w opisie zamieszczać zdjęcia lub grafiki - korzystaj z nich, gdy chcesz dodatkowo wyeksponować cechy produktu. A może tworzysz wideo produktowe? Załącz materiały, które pomogą klientowi podjąć decyzję o zakupie produktów w twoim sklepie internetowym.</span></p>', 299, '2020-06-08 09:17:57', NULL),
(97, 'Zegarek męski z dużą tarczą Smartwatch na pasku ze skóry ekologicznej', 10, '<p><span><strong>Opis produktu, który powie więcej, niż sprzedawca</strong><br /><br />W tym miejscu należy wstawić opis produktu, prezentujący jego cechy, właściwości oraz zastosowanie. Klient czytając opis musi dowiedzieć się o nim jak najwięcej. Pamiętaj, że to internet, a nie sklepowa półka. Produktu nie da się wziąć do ręki, dlatego opisz każdy szczegół najdokładniej jak potrafisz. Unikniesz w ten sposób<br />nieporozumień i zwrotów towaru.<br /><br /><strong>W opisie uwzględnij parametry techniczne, ale i opis zastosowania</strong><br /><br />Parametry warto wypunktować, by jak najbardziej ułatwić klientowi zrozumienie specyfiki produktu:<br /><br />- Rodzaj materiału<br />- Wymiary<br />- Kraj produkcji<br />- Dodatkowe właściwości<br />- Dodatkowe cechy charakterystyczne<br />- Dodatkowe informacje na temat wysyłki<br /><br /><strong>Dlaczego opis jest tak ważny</strong><br /><br />Forma przedstawienia asortymentu w sklepie internetowym ma znaczący wpływ na to, czy przekonamy klienta do zakupów w naszym sklepie. Zapewniając unikalne oraz wyczerpujące informacje na temat towaru, zwiększamy liczbę indeksowanych stron naszego sklepu przez wyszukiwarki internetowe np. Google. To właśnie wyszukiwarki zwiększają ruch w naszym sklepie, dlatego zadbajmy o to, aby każdy produkt posiadał wyczerpujący opis. <br /><br />Sklep internetowy, w odróżnieniu od tradycyjnego, nie posiada ekspedienta, który nas wysłucha oraz pomoże w wyborze przedmiotu spełniającego nasze oczekiwania. Istnieje duże prawdopodobieństwo, że klient, który nie znajdzie interesujących go informacji o produkcie, poszuka innego sklepu, a do nas już nie wróci. Opis zastępuje sprzedawcę i wzmacnia pozycję strony w wyszukiwarce - kieruj się tym podczas charakteryzowania produktu.<br /><br />Nie zapomnij o sekcji, która dodatkowo zachęci klienta do zrobienia zakupów u ciebie. Pamiętaj, że możesz w opisie zamieszczać zdjęcia lub grafiki - korzystaj z nich, gdy chcesz dodatkowo wyeksponować cechy produktu. A może tworzysz wideo produktowe? Załącz materiały, które pomogą klientowi podjąć decyzję o zakupie produktów w twoim sklepie internetowym.</span></p>', 329, '2020-06-08 09:20:02', NULL),
(98, 'Zegarek z błyszczącą tarczą Anette', 12, '<p><strong>Opis produktu, który powie więcej, niż sprzedawca</strong><br /><br />W tym miejscu należy wstawić opis produktu, prezentujący jego cechy, właściwości oraz zastosowanie. Klient czytając opis musi dowiedzieć się o nim jak najwięcej. Pamiętaj, że to internet, a nie sklepowa półka. Produktu nie da się wziąć do ręki, dlatego opisz każdy szczegół najdokładniej jak potrafisz. Unikniesz w ten sposób<br />nieporozumień i zwrotów towaru.<br /><br /><strong>W opisie uwzględnij parametry techniczne, ale i opis zastosowania</strong><br /><br />Parametry warto wypunktować, by jak najbardziej ułatwić klientowi zrozumienie specyfiki produktu:<br /><br />- Rodzaj materiału<br />- Wymiary<br />- Kraj produkcji<br />- Dodatkowe właściwości<br />- Dodatkowe cechy charakterystyczne<br />- Dodatkowe informacje na temat wysyłki<br /><br /><strong>Dlaczego opis jest tak ważny</strong><br /><br />Forma przedstawienia asortymentu w sklepie internetowym ma znaczący wpływ na to, czy przekonamy klienta do zakupów w naszym sklepie. Zapewniając unikalne oraz wyczerpujące informacje na temat towaru, zwiększamy liczbę indeksowanych stron naszego sklepu przez wyszukiwarki internetowe np. Google. To właśnie wyszukiwarki zwiększają ruch w naszym sklepie, dlatego zadbajmy o to, aby każdy produkt posiadał wyczerpujący opis. <br /><br />Sklep internetowy, w odróżnieniu od tradycyjnego, nie posiada ekspedienta, który nas wysłucha oraz pomoże w wyborze przedmiotu spełniającego nasze oczekiwania. Istnieje duże prawdopodobieństwo, że klient, który nie znajdzie interesujących go informacji o produkcie, poszuka innego sklepu, a do nas już nie wróci. Opis zastępuje sprzedawcę i wzmacnia pozycję strony w wyszukiwarce - kieruj się tym podczas charakteryzowania produktu.<br /><br />Nie zapomnij o sekcji, która dodatkowo zachęci klienta do zrobienia zakupów u ciebie. Pamiętaj, że możesz w opisie zamieszczać zdjęcia lub grafiki - korzystaj z nich, gdy chcesz dodatkowo wyeksponować cechy produktu. A może tworzysz wideo produktowe? Załącz materiały, które pomogą klientowi podjąć decyzję o zakupie produktów w twoim sklepie internetowym.</p>', 289, '2020-06-08 09:21:24', NULL),
(99, 'Pierścionek pozłacany z perłą słodkowodną', 12, '<p><strong>Opis produktu, który powie więcej, niż sprzedawca</strong><br /><br />W tym miejscu należy wstawić opis produktu, prezentujący jego cechy, właściwości oraz zastosowanie. Klient czytając opis musi dowiedzieć się o nim jak najwięcej. Pamiętaj, że to internet, a nie sklepowa półka. Produktu nie da się wziąć do ręki, dlatego opisz każdy szczegół najdokładniej jak potrafisz. Unikniesz w ten sposób<br />nieporozumień i zwrotów towaru.<br /><br /><strong>W opisie uwzględnij parametry techniczne, ale i opis zastosowania</strong><br /><br />Parametry warto wypunktować, by jak najbardziej ułatwić klientowi zrozumienie specyfiki produktu:<br /><br />- Rodzaj materiału<br />- Wymiary<br />- Kraj produkcji<br />- Dodatkowe właściwości<br />- Dodatkowe cechy charakterystyczne<br />- Dodatkowe informacje na temat wysyłki<br /><br /><strong>Dlaczego opis jest tak ważny</strong><br /><br />Forma przedstawienia asortymentu w sklepie internetowym ma znaczący wpływ na to, czy przekonamy klienta do zakupów w naszym sklepie. Zapewniając unikalne oraz wyczerpujące informacje na temat towaru, zwiększamy liczbę indeksowanych stron naszego sklepu przez wyszukiwarki internetowe np. Google. To właśnie wyszukiwarki zwiększają ruch w naszym sklepie, dlatego zadbajmy o to, aby każdy produkt posiadał wyczerpujący opis. <br /><br />Sklep internetowy, w odróżnieniu od tradycyjnego, nie posiada ekspedienta, który nas wysłucha oraz pomoże w wyborze przedmiotu spełniającego nasze oczekiwania. Istnieje duże prawdopodobieństwo, że klient, który nie znajdzie interesujących go informacji o produkcie, poszuka innego sklepu, a do nas już nie wróci. Opis zastępuje sprzedawcę i wzmacnia pozycję strony w wyszukiwarce - kieruj się tym podczas charakteryzowania produktu.<br /><br />Nie zapomnij o sekcji, która dodatkowo zachęci klienta do zrobienia zakupów u ciebie. Pamiętaj, że możesz w opisie zamieszczać zdjęcia lub grafiki - korzystaj z nich, gdy chcesz dodatkowo wyeksponować cechy produktu. A może tworzysz wideo produktowe? Załącz materiały, które pomogą klientowi podjąć decyzję o zakupie produktów w twoim sklepie internetowym.</p>', 129, '2020-06-08 09:41:42', NULL),
(100, 'Łańcuszek srebrny, celebrytka, 22 cm, z topazem', 12, '<p><strong>Opis produktu, który powie więcej, niż sprzedawca</strong><br /><br />W tym miejscu należy wstawić opis produktu, prezentujący jego cechy, właściwości oraz zastosowanie. Klient czytając opis musi dowiedzieć się o nim jak najwięcej. Pamiętaj, że to internet, a nie sklepowa półka. Produktu nie da się wziąć do ręki, dlatego opisz każdy szczegół najdokładniej jak potrafisz. Unikniesz w ten sposób<br />nieporozumień i zwrotów towaru.<br /><br /><strong>W opisie uwzględnij parametry techniczne, ale i opis zastosowania</strong><br /><br />Parametry warto wypunktować, by jak najbardziej ułatwić klientowi zrozumienie specyfiki produktu:<br /><br />- Rodzaj materiału<br />- Wymiary<br />- Kraj produkcji<br />- Dodatkowe właściwości<br />- Dodatkowe cechy charakterystyczne<br />- Dodatkowe informacje na temat wysyłki<br /><br /><strong>Dlaczego opis jest tak ważny</strong><br /><br />Forma przedstawienia asortymentu w sklepie internetowym ma znaczący wpływ na to, czy przekonamy klienta do zakupów w naszym sklepie. Zapewniając unikalne oraz wyczerpujące informacje na temat towaru, zwiększamy liczbę indeksowanych stron naszego sklepu przez wyszukiwarki internetowe np. Google. To właśnie wyszukiwarki zwiększają ruch w naszym sklepie, dlatego zadbajmy o to, aby każdy produkt posiadał wyczerpujący opis. <br /><br />Sklep internetowy, w odróżnieniu od tradycyjnego, nie posiada ekspedienta, który nas wysłucha oraz pomoże w wyborze przedmiotu spełniającego nasze oczekiwania. Istnieje duże prawdopodobieństwo, że klient, który nie znajdzie interesujących go informacji o produkcie, poszuka innego sklepu, a do nas już nie wróci. Opis zastępuje sprzedawcę i wzmacnia pozycję strony w wyszukiwarce - kieruj się tym podczas charakteryzowania produktu.<br /><br />Nie zapomnij o sekcji, która dodatkowo zachęci klienta do zrobienia zakupów u ciebie. Pamiętaj, że możesz w opisie zamieszczać zdjęcia lub grafiki - korzystaj z nich, gdy chcesz dodatkowo wyeksponować cechy produktu. A może tworzysz wideo produktowe? Załącz materiały, które pomogą klientowi podjąć decyzję o zakupie produktów w twoim sklepie internetowym.</p>', 129, '2020-06-08 09:45:04', NULL),
(101, 'Welurowa opaska do włosów z węzłem', 12, '<p><strong>Opis produktu, który powie więcej, niż sprzedawca</strong><br /><br />W tym miejscu należy wstawić opis produktu, prezentujący jego cechy, właściwości oraz zastosowanie. Klient czytając opis musi dowiedzieć się o nim jak najwięcej. Pamiętaj, że to internet, a nie sklepowa półka. Produktu nie da się wziąć do ręki, dlatego opisz każdy szczegół najdokładniej jak potrafisz. Unikniesz w ten sposób<br />nieporozumień i zwrotów towaru.<br /><br /><strong>W opisie uwzględnij parametry techniczne, ale i opis zastosowania</strong><br /><br />Parametry warto wypunktować, by jak najbardziej ułatwić klientowi zrozumienie specyfiki produktu:<br /><br />- Rodzaj materiału<br />- Wymiary<br />- Kraj produkcji<br />- Dodatkowe właściwości<br />- Dodatkowe cechy charakterystyczne<br />- Dodatkowe informacje na temat wysyłki<br /><br /><strong>Dlaczego opis jest tak ważny</strong><br /><br />Forma przedstawienia asortymentu w sklepie internetowym ma znaczący wpływ na to, czy przekonamy klienta do zakupów w naszym sklepie. Zapewniając unikalne oraz wyczerpujące informacje na temat towaru, zwiększamy liczbę indeksowanych stron naszego sklepu przez wyszukiwarki internetowe np. Google. To właśnie wyszukiwarki zwiększają ruch w naszym sklepie, dlatego zadbajmy o to, aby każdy produkt posiadał wyczerpujący opis. <br /><br />Sklep internetowy, w odróżnieniu od tradycyjnego, nie posiada ekspedienta, który nas wysłucha oraz pomoże w wyborze przedmiotu spełniającego nasze oczekiwania. Istnieje duże prawdopodobieństwo, że klient, który nie znajdzie interesujących go informacji o produkcie, poszuka innego sklepu, a do nas już nie wróci. Opis zastępuje sprzedawcę i wzmacnia pozycję strony w wyszukiwarce - kieruj się tym podczas charakteryzowania produktu.<br /><br />Nie zapomnij o sekcji, która dodatkowo zachęci klienta do zrobienia zakupów u ciebie. Pamiętaj, że możesz w opisie zamieszczać zdjęcia lub grafiki - korzystaj z nich, gdy chcesz dodatkowo wyeksponować cechy produktu. A może tworzysz wideo produktowe? Załącz materiały, które pomogą klientowi podjąć decyzję o zakupie produktów w twoim sklepie internetowym.</p>', 39.99, '2020-06-08 09:45:50', NULL),
(102, 'Czarna torba typu shopper zamszowa', 15, '<p><strong>Opis produktu, który powie więcej, niż sprzedawca</strong><br /><br />W tym miejscu należy wstawić opis produktu, prezentujący jego cechy, właściwości oraz zastosowanie. Klient czytając opis musi dowiedzieć się o nim jak najwięcej. Pamiętaj, że to internet, a nie sklepowa półka. Produktu nie da się wziąć do ręki, dlatego opisz każdy szczegół najdokładniej jak potrafisz. Unikniesz w ten sposób<br />nieporozumień i zwrotów towaru.<br /><br /><strong>W opisie uwzględnij parametry techniczne, ale i opis zastosowania</strong><br /><br />Parametry warto wypunktować, by jak najbardziej ułatwić klientowi zrozumienie specyfiki produktu:<br /><br />- Rodzaj materiału<br />- Wymiary<br />- Kraj produkcji<br />- Dodatkowe właściwości<br />- Dodatkowe cechy charakterystyczne<br />- Dodatkowe informacje na temat wysyłki<br /><br /><strong>Dlaczego opis jest tak ważny</strong><br /><br />Forma przedstawienia asortymentu w sklepie internetowym ma znaczący wpływ na to, czy przekonamy klienta do zakupów w naszym sklepie. Zapewniając unikalne oraz wyczerpujące informacje na temat towaru, zwiększamy liczbę indeksowanych stron naszego sklepu przez wyszukiwarki internetowe np. Google. To właśnie wyszukiwarki zwiększają ruch w naszym sklepie, dlatego zadbajmy o to, aby każdy produkt posiadał wyczerpujący opis. <br /><br />Sklep internetowy, w odróżnieniu od tradycyjnego, nie posiada ekspedienta, który nas wysłucha oraz pomoże w wyborze przedmiotu spełniającego nasze oczekiwania. Istnieje duże prawdopodobieństwo, że klient, który nie znajdzie interesujących go informacji o produkcie, poszuka innego sklepu, a do nas już nie wróci. Opis zastępuje sprzedawcę i wzmacnia pozycję strony w wyszukiwarce - kieruj się tym podczas charakteryzowania produktu.<br /><br />Nie zapomnij o sekcji, która dodatkowo zachęci klienta do zrobienia zakupów u ciebie. Pamiętaj, że możesz w opisie zamieszczać zdjęcia lub grafiki - korzystaj z nich, gdy chcesz dodatkowo wyeksponować cechy produktu. A może tworzysz wideo produktowe? Załącz materiały, które pomogą klientowi podjąć decyzję o zakupie produktów w twoim sklepie internetowym.</p>', 99, '2020-06-08 11:00:05', NULL),
(103, 'Torebka listonoszka ze skóry ekologicznej', 15, '<p><strong>Opis produktu, który powie więcej, niż sprzedawca</strong><br /><br />W tym miejscu należy wstawić opis produktu, prezentujący jego cechy, właściwości oraz zastosowanie. Klient czytając opis musi dowiedzieć się o nim jak najwięcej. Pamiętaj, że to internet, a nie sklepowa półka. Produktu nie da się wziąć do ręki, dlatego opisz każdy szczegół najdokładniej jak potrafisz. Unikniesz w ten sposób<br />nieporozumień i zwrotów towaru.<br /><br /><strong>W opisie uwzględnij parametry techniczne, ale i opis zastosowania</strong><br /><br />Parametry warto wypunktować, by jak najbardziej ułatwić klientowi zrozumienie specyfiki produktu:<br /><br />- Rodzaj materiału<br />- Wymiary<br />- Kraj produkcji<br />- Dodatkowe właściwości<br />- Dodatkowe cechy charakterystyczne<br />- Dodatkowe informacje na temat wysyłki<br /><br /><strong>Dlaczego opis jest tak ważny</strong><br /><br />Forma przedstawienia asortymentu w sklepie internetowym ma znaczący wpływ na to, czy przekonamy klienta do zakupów w naszym sklepie. Zapewniając unikalne oraz wyczerpujące informacje na temat towaru, zwiększamy liczbę indeksowanych stron naszego sklepu przez wyszukiwarki internetowe np. Google. To właśnie wyszukiwarki zwiększają ruch w naszym sklepie, dlatego zadbajmy o to, aby każdy produkt posiadał wyczerpujący opis. <br /><br />Sklep internetowy, w odróżnieniu od tradycyjnego, nie posiada ekspedienta, który nas wysłucha oraz pomoże w wyborze przedmiotu spełniającego nasze oczekiwania. Istnieje duże prawdopodobieństwo, że klient, który nie znajdzie interesujących go informacji o produkcie, poszuka innego sklepu, a do nas już nie wróci. Opis zastępuje sprzedawcę i wzmacnia pozycję strony w wyszukiwarce - kieruj się tym podczas charakteryzowania produktu.<br /><br />Nie zapomnij o sekcji, która dodatkowo zachęci klienta do zrobienia zakupów u ciebie. Pamiętaj, że możesz w opisie zamieszczać zdjęcia lub grafiki - korzystaj z nich, gdy chcesz dodatkowo wyeksponować cechy produktu. A może tworzysz wideo produktowe? Załącz materiały, które pomogą klientowi podjąć decyzję o zakupie produktów w twoim sklepie internetowym.</p>', 199, '2020-06-08 11:01:10', NULL),
(104, 'Czółenka klasyczne lakierowane beżowe', 8, '<p><strong>Opis produktu, który powie więcej, niż sprzedawca</strong><br /><br />W tym miejscu należy wstawić opis produktu, prezentujący jego cechy, właściwości oraz zastosowanie. Klient czytając opis musi dowiedzieć się o nim jak najwięcej. Pamiętaj, że to internet, a nie sklepowa półka. Produktu nie da się wziąć do ręki, dlatego opisz każdy szczegół najdokładniej jak potrafisz. Unikniesz w ten sposób<br />nieporozumień i zwrotów towaru.<br /><br /><strong>W opisie uwzględnij parametry techniczne, ale i opis zastosowania</strong><br /><br />Parametry warto wypunktować, by jak najbardziej ułatwić klientowi zrozumienie specyfiki produktu:<br /><br />- Rodzaj materiału<br />- Wymiary<br />- Kraj produkcji<br />- Dodatkowe właściwości<br />- Dodatkowe cechy charakterystyczne<br />- Dodatkowe informacje na temat wysyłki<br /><br /><strong>Dlaczego opis jest tak ważny</strong><br /><br />Forma przedstawienia asortymentu w sklepie internetowym ma znaczący wpływ na to, czy przekonamy klienta do zakupów w naszym sklepie. Zapewniając unikalne oraz wyczerpujące informacje na temat towaru, zwiększamy liczbę indeksowanych stron naszego sklepu przez wyszukiwarki internetowe np. Google. To właśnie wyszukiwarki zwiększają ruch w naszym sklepie, dlatego zadbajmy o to, aby każdy produkt posiadał wyczerpujący opis. <br /><br />Sklep internetowy, w odróżnieniu od tradycyjnego, nie posiada ekspedienta, który nas wysłucha oraz pomoże w wyborze przedmiotu spełniającego nasze oczekiwania. Istnieje duże prawdopodobieństwo, że klient, który nie znajdzie interesujących go informacji o produkcie, poszuka innego sklepu, a do nas już nie wróci. Opis zastępuje sprzedawcę i wzmacnia pozycję strony w wyszukiwarce - kieruj się tym podczas charakteryzowania produktu.<br /><br />Nie zapomnij o sekcji, która dodatkowo zachęci klienta do zrobienia zakupów u ciebie. Pamiętaj, że możesz w opisie zamieszczać zdjęcia lub grafiki - korzystaj z nich, gdy chcesz dodatkowo wyeksponować cechy produktu. A może tworzysz wideo produktowe? Załącz materiały, które pomogą klientowi podjąć decyzję o zakupie produktów w twoim sklepie internetowym.</p>', 69, '2020-06-08 11:16:14', NULL),
(105, 'Balerinki zamszowe Bumblebee', 8, '<p><strong>Opis produktu, który powie więcej, niż sprzedawca</strong><br /><br />W tym miejscu należy wstawić opis produktu, prezentujący jego cechy, właściwości oraz zastosowanie. Klient czytając opis musi dowiedzieć się o nim jak najwięcej. Pamiętaj, że to internet, a nie sklepowa półka. Produktu nie da się wziąć do ręki, dlatego opisz każdy szczegół najdokładniej jak potrafisz. Unikniesz w ten sposób<br />nieporozumień i zwrotów towaru.<br /><br /><strong>W opisie uwzględnij parametry techniczne, ale i opis zastosowania</strong><br /><br />Parametry warto wypunktować, by jak najbardziej ułatwić klientowi zrozumienie specyfiki produktu:<br /><br />- Rodzaj materiału<br />- Wymiary<br />- Kraj produkcji<br />- Dodatkowe właściwości<br />- Dodatkowe cechy charakterystyczne<br />- Dodatkowe informacje na temat wysyłki<br /><br /><strong>Dlaczego opis jest tak ważny</strong><br /><br />Forma przedstawienia asortymentu w sklepie internetowym ma znaczący wpływ na to, czy przekonamy klienta do zakupów w naszym sklepie. Zapewniając unikalne oraz wyczerpujące informacje na temat towaru, zwiększamy liczbę indeksowanych stron naszego sklepu przez wyszukiwarki internetowe np. Google. To właśnie wyszukiwarki zwiększają ruch w naszym sklepie, dlatego zadbajmy o to, aby każdy produkt posiadał wyczerpujący opis. <br /><br />Sklep internetowy, w odróżnieniu od tradycyjnego, nie posiada ekspedienta, który nas wysłucha oraz pomoże w wyborze przedmiotu spełniającego nasze oczekiwania. Istnieje duże prawdopodobieństwo, że klient, który nie znajdzie interesujących go informacji o produkcie, poszuka innego sklepu, a do nas już nie wróci. Opis zastępuje sprzedawcę i wzmacnia pozycję strony w wyszukiwarce - kieruj się tym podczas charakteryzowania produktu.<br /><br />Nie zapomnij o sekcji, która dodatkowo zachęci klienta do zrobienia zakupów u ciebie. Pamiętaj, że możesz w opisie zamieszczać zdjęcia lub grafiki - korzystaj z nich, gdy chcesz dodatkowo wyeksponować cechy produktu. A może tworzysz wideo produktowe? Załącz materiały, które pomogą klientowi podjąć decyzję o zakupie produktów w twoim sklepie internetowym.</p>', 39, '2020-06-08 11:19:20', NULL),
(106, 'Trampki kolorowe przed kostkę', 8, '<p><strong>Opis produktu, który powie więcej, niż sprzedawca</strong><br /><br />W tym miejscu należy wstawić opis produktu, prezentujący jego cechy, właściwości oraz zastosowanie. Klient czytając opis musi dowiedzieć się o nim jak najwięcej. Pamiętaj, że to internet, a nie sklepowa półka. Produktu nie da się wziąć do ręki, dlatego opisz każdy szczegół najdokładniej jak potrafisz. Unikniesz w ten sposób<br />nieporozumień i zwrotów towaru.<br /><br /><strong>W opisie uwzględnij parametry techniczne, ale i opis zastosowania</strong><br /><br />Parametry warto wypunktować, by jak najbardziej ułatwić klientowi zrozumienie specyfiki produktu:<br /><br />- Rodzaj materiału<br />- Wymiary<br />- Kraj produkcji<br />- Dodatkowe właściwości<br />- Dodatkowe cechy charakterystyczne<br />- Dodatkowe informacje na temat wysyłki<br /><br /><strong>Dlaczego opis jest tak ważny</strong><br /><br />Forma przedstawienia asortymentu w sklepie internetowym ma znaczący wpływ na to, czy przekonamy klienta do zakupów w naszym sklepie. Zapewniając unikalne oraz wyczerpujące informacje na temat towaru, zwiększamy liczbę indeksowanych stron naszego sklepu przez wyszukiwarki internetowe np. Google. To właśnie wyszukiwarki zwiększają ruch w naszym sklepie, dlatego zadbajmy o to, aby każdy produkt posiadał wyczerpujący opis. <br /><br />Sklep internetowy, w odróżnieniu od tradycyjnego, nie posiada ekspedienta, który nas wysłucha oraz pomoże w wyborze przedmiotu spełniającego nasze oczekiwania. Istnieje duże prawdopodobieństwo, że klient, który nie znajdzie interesujących go informacji o produkcie, poszuka innego sklepu, a do nas już nie wróci. Opis zastępuje sprzedawcę i wzmacnia pozycję strony w wyszukiwarce - kieruj się tym podczas charakteryzowania produktu.<br /><br />Nie zapomnij o sekcji, która dodatkowo zachęci klienta do zrobienia zakupów u ciebie. Pamiętaj, że możesz w opisie zamieszczać zdjęcia lub grafiki - korzystaj z nich, gdy chcesz dodatkowo wyeksponować cechy produktu. A może tworzysz wideo produktowe? Załącz materiały, które pomogą klientowi podjąć decyzję o zakupie produktów w twoim sklepie internetowym.</p>', 45, '2020-06-08 11:20:38', NULL),
(107, 'Trampki biało-czarne wysokie Dr Tomz', 7, '<p><strong>Opis produktu, który powie więcej, niż sprzedawca</strong><br /><br />W tym miejscu należy wstawić opis produktu, prezentujący jego cechy, właściwości oraz zastosowanie. Klient czytając opis musi dowiedzieć się o nim jak najwięcej. Pamiętaj, że to internet, a nie sklepowa półka. Produktu nie da się wziąć do ręki, dlatego opisz każdy szczegół najdokładniej jak potrafisz. Unikniesz w ten sposób<br />nieporozumień i zwrotów towaru.<br /><br /><strong>W opisie uwzględnij parametry techniczne, ale i opis zastosowania</strong><br /><br />Parametry warto wypunktować, by jak najbardziej ułatwić klientowi zrozumienie specyfiki produktu:<br /><br />- Rodzaj materiału<br />- Wymiary<br />- Kraj produkcji<br />- Dodatkowe właściwości<br />- Dodatkowe cechy charakterystyczne<br />- Dodatkowe informacje na temat wysyłki<br /><br /><strong>Dlaczego opis jest tak ważny</strong><br /><br />Forma przedstawienia asortymentu w sklepie internetowym ma znaczący wpływ na to, czy przekonamy klienta do zakupów w naszym sklepie. Zapewniając unikalne oraz wyczerpujące informacje na temat towaru, zwiększamy liczbę indeksowanych stron naszego sklepu przez wyszukiwarki internetowe np. Google. To właśnie wyszukiwarki zwiększają ruch w naszym sklepie, dlatego zadbajmy o to, aby każdy produkt posiadał wyczerpujący opis. <br /><br />Sklep internetowy, w odróżnieniu od tradycyjnego, nie posiada ekspedienta, który nas wysłucha oraz pomoże w wyborze przedmiotu spełniającego nasze oczekiwania. Istnieje duże prawdopodobieństwo, że klient, który nie znajdzie interesujących go informacji o produkcie, poszuka innego sklepu, a do nas już nie wróci. Opis zastępuje sprzedawcę i wzmacnia pozycję strony w wyszukiwarce - kieruj się tym podczas charakteryzowania produktu.<br /><br />Nie zapomnij o sekcji, która dodatkowo zachęci klienta do zrobienia zakupów u ciebie. Pamiętaj, że możesz w opisie zamieszczać zdjęcia lub grafiki - korzystaj z nich, gdy chcesz dodatkowo wyeksponować cechy produktu. A może tworzysz wideo produktowe? Załącz materiały, które pomogą klientowi podjąć decyzję o zakupie produktów w twoim sklepie internetowym.</p>', 89, '2020-06-08 11:21:22', NULL),
(108, 'Eleganckie trampki z ozdobnymi sznurówkami', 8, '<p><strong>Opis produktu, który powie więcej, niż sprzedawca</strong><br /><br />W tym miejscu należy wstawić opis produktu, prezentujący jego cechy, właściwości oraz zastosowanie. Klient czytając opis musi dowiedzieć się o nim jak najwięcej. Pamiętaj, że to internet, a nie sklepowa półka. Produktu nie da się wziąć do ręki, dlatego opisz każdy szczegół najdokładniej jak potrafisz. Unikniesz w ten sposób<br />nieporozumień i zwrotów towaru.<br /><br /><strong>W opisie uwzględnij parametry techniczne, ale i opis zastosowania</strong><br /><br />Parametry warto wypunktować, by jak najbardziej ułatwić klientowi zrozumienie specyfiki produktu:<br /><br />- Rodzaj materiału<br />- Wymiary<br />- Kraj produkcji<br />- Dodatkowe właściwości<br />- Dodatkowe cechy charakterystyczne<br />- Dodatkowe informacje na temat wysyłki<br /><br /><strong>Dlaczego opis jest tak ważny</strong><br /><br />Forma przedstawienia asortymentu w sklepie internetowym ma znaczący wpływ na to, czy przekonamy klienta do zakupów w naszym sklepie. Zapewniając unikalne oraz wyczerpujące informacje na temat towaru, zwiększamy liczbę indeksowanych stron naszego sklepu przez wyszukiwarki internetowe np. Google. To właśnie wyszukiwarki zwiększają ruch w naszym sklepie, dlatego zadbajmy o to, aby każdy produkt posiadał wyczerpujący opis. <br /><br />Sklep internetowy, w odróżnieniu od tradycyjnego, nie posiada ekspedienta, który nas wysłucha oraz pomoże w wyborze przedmiotu spełniającego nasze oczekiwania. Istnieje duże prawdopodobieństwo, że klient, który nie znajdzie interesujących go informacji o produkcie, poszuka innego sklepu, a do nas już nie wróci. Opis zastępuje sprzedawcę i wzmacnia pozycję strony w wyszukiwarce - kieruj się tym podczas charakteryzowania produktu.<br /><br />Nie zapomnij o sekcji, która dodatkowo zachęci klienta do zrobienia zakupów u ciebie. Pamiętaj, że możesz w opisie zamieszczać zdjęcia lub grafiki - korzystaj z nich, gdy chcesz dodatkowo wyeksponować cechy produktu. A może tworzysz wideo produktowe? Załącz materiały, które pomogą klientowi podjąć decyzję o zakupie produktów w twoim sklepie internetowym.</p>', 229, '2020-06-08 11:29:10', NULL),
(109, 'Sneakersy sportowe z kolorowymi wstawkami', 7, '<p><strong>Opis produktu, który powie więcej, niż sprzedawca</strong><br /><br />W tym miejscu należy wstawić opis produktu, prezentujący jego cechy, właściwości oraz zastosowanie. Klient czytając opis musi dowiedzieć się o nim jak najwięcej. Pamiętaj, że to internet, a nie sklepowa półka. Produktu nie da się wziąć do ręki, dlatego opisz każdy szczegół najdokładniej jak potrafisz. Unikniesz w ten sposób<br />nieporozumień i zwrotów towaru.<br /><br /><strong>W opisie uwzględnij parametry techniczne, ale i opis zastosowania</strong><br /><br />Parametry warto wypunktować, by jak najbardziej ułatwić klientowi zrozumienie specyfiki produktu:<br /><br />- Rodzaj materiału<br />- Wymiary<br />- Kraj produkcji<br />- Dodatkowe właściwości<br />- Dodatkowe cechy charakterystyczne<br />- Dodatkowe informacje na temat wysyłki<br /><br /><strong>Dlaczego opis jest tak ważny</strong><br /><br />Forma przedstawienia asortymentu w sklepie internetowym ma znaczący wpływ na to, czy przekonamy klienta do zakupów w naszym sklepie. Zapewniając unikalne oraz wyczerpujące informacje na temat towaru, zwiększamy liczbę indeksowanych stron naszego sklepu przez wyszukiwarki internetowe np. Google. To właśnie wyszukiwarki zwiększają ruch w naszym sklepie, dlatego zadbajmy o to, aby każdy produkt posiadał wyczerpujący opis. <br /><br />Sklep internetowy, w odróżnieniu od tradycyjnego, nie posiada ekspedienta, który nas wysłucha oraz pomoże w wyborze przedmiotu spełniającego nasze oczekiwania. Istnieje duże prawdopodobieństwo, że klient, który nie znajdzie interesujących go informacji o produkcie, poszuka innego sklepu, a do nas już nie wróci. Opis zastępuje sprzedawcę i wzmacnia pozycję strony w wyszukiwarce - kieruj się tym podczas charakteryzowania produktu.<br /><br />Nie zapomnij o sekcji, która dodatkowo zachęci klienta do zrobienia zakupów u ciebie. Pamiętaj, że możesz w opisie zamieszczać zdjęcia lub grafiki - korzystaj z nich, gdy chcesz dodatkowo wyeksponować cechy produktu. A może tworzysz wideo produktowe? Załącz materiały, które pomogą klientowi podjąć decyzję o zakupie produktów w twoim sklepie internetowym.</p>', 99, '2020-06-08 11:29:22', NULL),
(110, 'Sneakersy Dr Tomz z grubą podeszwą', 7, '<p><strong>Opis produktu, który powie więcej, niż sprzedawca</strong><br /><br />W tym miejscu należy wstawić opis produktu, prezentujący jego cechy, właściwości oraz zastosowanie. Klient czytając opis musi dowiedzieć się o nim jak najwięcej. Pamiętaj, że to internet, a nie sklepowa półka. Produktu nie da się wziąć do ręki, dlatego opisz każdy szczegół najdokładniej jak potrafisz. Unikniesz w ten sposób<br />nieporozumień i zwrotów towaru.<br /><br /><strong>W opisie uwzględnij parametry techniczne, ale i opis zastosowania</strong><br /><br />Parametry warto wypunktować, by jak najbardziej ułatwić klientowi zrozumienie specyfiki produktu:<br /><br />- Rodzaj materiału<br />- Wymiary<br />- Kraj produkcji<br />- Dodatkowe właściwości<br />- Dodatkowe cechy charakterystyczne<br />- Dodatkowe informacje na temat wysyłki<br /><br /><strong>Dlaczego opis jest tak ważny</strong><br /><br />Forma przedstawienia asortymentu w sklepie internetowym ma znaczący wpływ na to, czy przekonamy klienta do zakupów w naszym sklepie. Zapewniając unikalne oraz wyczerpujące informacje na temat towaru, zwiększamy liczbę indeksowanych stron naszego sklepu przez wyszukiwarki internetowe np. Google. To właśnie wyszukiwarki zwiększają ruch w naszym sklepie, dlatego zadbajmy o to, aby każdy produkt posiadał wyczerpujący opis. <br /><br />Sklep internetowy, w odróżnieniu od tradycyjnego, nie posiada ekspedienta, który nas wysłucha oraz pomoże w wyborze przedmiotu spełniającego nasze oczekiwania. Istnieje duże prawdopodobieństwo, że klient, który nie znajdzie interesujących go informacji o produkcie, poszuka innego sklepu, a do nas już nie wróci. Opis zastępuje sprzedawcę i wzmacnia pozycję strony w wyszukiwarce - kieruj się tym podczas charakteryzowania produktu.<br /><br />Nie zapomnij o sekcji, która dodatkowo zachęci klienta do zrobienia zakupów u ciebie. Pamiętaj, że możesz w opisie zamieszczać zdjęcia lub grafiki - korzystaj z nich, gdy chcesz dodatkowo wyeksponować cechy produktu. A może tworzysz wideo produktowe? Załącz materiały, które pomogą klientowi podjąć decyzję o zakupie produktów w twoim sklepie internetowym.</p>', 369, '2020-06-08 11:31:43', NULL),
(111, 'Spodnie materiałowe casual Yan', 3, '<p><strong>Opis produktu, który powie więcej, niż sprzedawca</strong><br /><br />W tym miejscu należy wstawić opis produktu, prezentujący jego cechy, właściwości oraz zastosowanie. Klient czytając opis musi dowiedzieć się o nim jak najwięcej. Pamiętaj, że to internet, a nie sklepowa półka. Produktu nie da się wziąć do ręki, dlatego opisz każdy szczegół najdokładniej jak potrafisz. Unikniesz w ten sposób<br />nieporozumień i zwrotów towaru.<br /><br /><strong>W opisie uwzględnij parametry techniczne, ale i opis zastosowania</strong><br /><br />Parametry warto wypunktować, by jak najbardziej ułatwić klientowi zrozumienie specyfiki produktu:<br /><br />- Rodzaj materiału<br />- Wymiary<br />- Kraj produkcji<br />- Dodatkowe właściwości<br />- Dodatkowe cechy charakterystyczne<br />- Dodatkowe informacje na temat wysyłki<br /><br /><strong>Dlaczego opis jest tak ważny</strong><br /><br />Forma przedstawienia asortymentu w sklepie internetowym ma znaczący wpływ na to, czy przekonamy klienta do zakupów w naszym sklepie. Zapewniając unikalne oraz wyczerpujące informacje na temat towaru, zwiększamy liczbę indeksowanych stron naszego sklepu przez wyszukiwarki internetowe np. Google. To właśnie wyszukiwarki zwiększają ruch w naszym sklepie, dlatego zadbajmy o to, aby każdy produkt posiadał wyczerpujący opis. <br /><br />Sklep internetowy, w odróżnieniu od tradycyjnego, nie posiada ekspedienta, który nas wysłucha oraz pomoże w wyborze przedmiotu spełniającego nasze oczekiwania. Istnieje duże prawdopodobieństwo, że klient, który nie znajdzie interesujących go informacji o produkcie, poszuka innego sklepu, a do nas już nie wróci. Opis zastępuje sprzedawcę i wzmacnia pozycję strony w wyszukiwarce - kieruj się tym podczas charakteryzowania produktu.<br /><br />Nie zapomnij o sekcji, która dodatkowo zachęci klienta do zrobienia zakupów u ciebie. Pamiętaj, że możesz w opisie zamieszczać zdjęcia lub grafiki - korzystaj z nich, gdy chcesz dodatkowo wyeksponować cechy produktu. A może tworzysz wideo produktowe? Załącz materiały, które pomogą klientowi podjąć decyzję o zakupie produktów w twoim sklepie internetowym.</p>', 149, '2020-06-08 12:08:13', NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `info`
--
ALTER TABLE `info`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`),
  ADD KEY `category_id` (`category_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `categories`
--
ALTER TABLE `categories`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=35;

--
-- AUTO_INCREMENT for table `info`
--
ALTER TABLE `info`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=112;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `products`
--
ALTER TABLE `products`
  ADD CONSTRAINT `products_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
